packages:
  - apps/*
  - packages/*
catalog:
  "@neondatabase/serverless": ^0.10.1
  "@oslojs/crypto": ^1.0.1
  "@oslojs/encoding": ^1.1.0
  "@types/bun": ^1.1.16
  "@types/uuid": ^10.0.0
  "@typescript-eslint/eslint-plugin": ^7.1.0
  "@typescript-eslint/parser": ^7.1.0
  "@rocicorp/zero": ~0.16
  arctic: ^2.0.1
  better-auth: ^1.2.3
  dotenv: ^16.4.5
  drizzle-kit: ^0.30.1
  drizzle-orm: ^0.38.3
  hono: ^4.6.6
  motion: 12.4.7
  turbo: ^2.2.3
  uuid: ^10.0.0
  typescript: ^5.6.3
  tailwindcss: ^3.4.14
  "@types/react": ^19
  "@types/react-dom": ^19
  react: ^19
  react-dom: ^19
  next: ~15.2.1
