name: Migrate database

concurrency:
  group: "release-${{ github.ref }}" # Groups runs by the branch reference
  cancel-in-progress: false # Queues new runs instead of canceling

on:
  workflow_dispatch:

jobs:
  run-migrations:
    name: Run migrations
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          architecture: "x64"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Migrate database
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          CI: true
        run: |
          echo "DATABASE_URL=$DATABASE_URL" >> packages/database/.env
          echo "CI=$CI" >> packages/database/.env
          pnpm run db:migrate
          rm packages/database/.env

      - name: Bump Zero schema version
        env:
          ZERO_UPSTREAM_DB: ${{ secrets.DATABASE_URL }}
        run: |
          echo "ZERO_UPSTREAM_DB=$ZERO_UPSTREAM_DB" >> packages/zero/.env
          echo "CI=$CI" >> packages/zero/.env

          pnpm run zero:migrate

      - name: Deploy latest Zero permissions
        env:
          ZERO_UPSTREAM_DB: ${{ secrets.DATABASE_URL }}
        run: |
          # build database before deploying; otherwise drizzle schema won't load
          pnpm turbo @avelin/database#build

          pnpm run zero:deploy-permissions
          rm packages/zero/.env
